In [3]:
%load_ext autoreload
%autoreload 2

In [7]:
from alpaca.data.historical import CryptoHistoricalDataClient
from alpaca.data.requests import CryptoBarsRequest
from alpaca.data.timeframe import TimeFrame
from datetime import datetime

# no keys required for crypto data
client = CryptoHistoricalDataClient()

start = datetime(year=2022,
                 month=7,
                 day=1)

request_params = CryptoBarsRequest(
                        symbol_or_symbols=["BTC/USD", "ETH/USD"],
                        timeframe=TimeFrame.Day,
                        start=start
                 )

bars = client.get_crypto_bars(request_params)

In [15]:
bars.df

                                       open      high       low     close  \
symbol  timestamp
BTC/USD 2022-07-01 05:00:00+00:00  19381.00  19772.00  18953.00  19176.00
        2022-07-02 05:00:00+00:00  19173.00  19421.00  18767.00  19189.00
        2022-07-03 05:00:00+00:00  19242.00  19626.00  18918.00  19101.00
        2022-07-04 05:00:00+00:00  19102.00  20451.00  19064.00  20253.00
        2022-07-05 05:00:00+00:00  20253.00  20722.00  19285.00  20074.00
...                                     ...       ...       ...       ...
ETH/USD 2023-03-03 06:00:00+00:00   1567.13   1580.53   1547.28   1567.04
        2023-03-04 06:00:00+00:00   1567.30   1588.40   1549.16   1570.22
        2023-03-05 06:00:00+00:00   1570.37   1578.50   1554.71   1560.39
        2023-03-06 06:00:00+00:00   1560.26   1583.85   1557.71   1574.05
        2023-03-07 06:00:00+00:00   1574.04   1574.32   1536.12   1560.00

                                        volume  trade_count          vwap
symbol  timestamp
BTC/USD 2022-07-01 05:00:00+00:00   1643.67920       7718.0  19372.984712
        2022-07-02 05:00:00+00:00    758.37790       3942.0  19173.157709
        2022-07-03 05:00:00+00:00    706.13350       3603.0  19233.413139
        2022-07-04 05:00:00+00:00   2175.97410      11129.0  19802.847593
        2022-07-05 05:00:00+00:00   2346.27990      12902.0  19888.640195
...                                        ...          ...           ...
ETH/USD 2023-03-03 06:00:00+00:00  74837.14483      88320.0   1566.585684
        2023-03-04 06:00:00+00:00  43871.83670      60850.0   1568.260492
        2023-03-05 06:00:00+00:00  54412.30930      71753.0   1565.530712
        2023-03-06 06:00:00+00:00  58675.40690      68300.0   1569.261867
        2023-03-07 06:00:00+00:00  69799.60840      79402.0   1557.739490

[500 rows x 7 columns]